name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Start Application
        run: |
          java -jar target/my-app.jar &
          echo $! > app.pid
        env:
          SPRING_PROFILES_ACTIVE: ci

      - name: Wait for Application to Start
        run: |
          
          for i in {1..30}; do
            if nc -z localhost 7070; then
              echo "Application started"
              break
            fi
            echo "Waiting for application..."
            sleep 1
          done

      - name: Install k6
        run: sudo snap install k6

      - name: Run k6 Performance Tests
        run: k6 run --out json=report.json script.js

      - name: Upload k6 Test Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: report.json

      - name: Stop Application
        run: kill $(cat app.pid)